# path to a directory with all packages
storage: ./storage

web:
  enable: true
  title: Verdaccio - NPM registry
  logo: logo.png

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

auth:
  gitlab:
    url: https://gitlab.com

packages:
   # scoped packages
   '@*/*':
     access: $all
     publish: $authenticated
     proxy: npmjs
     gitlab: true

   '**':
     access: $all
     publish: $authenticated
     proxy: npmjs
     gitlab: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}

listen:
  - 0.0.0.0:4873
