version: '3'

services:
  verdaccio:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4873:4873"
    environment:
      - verdaccio_auth__gitlab__url=https://gitlab.com